######################################################################
# Automatically generated by qmake (2.01a) søn sep. 9 21:10:22 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += touchkeyboardactivity.cpp
